# src/main/resources/application.properties

# PostgreSQL Connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/song_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Tell Hibernate to use the PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create or update the tables based on your Song.java entity
spring.jpa.hibernate.ddl-auto=update